# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networkstuff.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='networkstuff.proto',
  package='networkstuff',
  syntax='proto3',
  serialized_options=b'Z\037github.com/package/networkstuff',
  serialized_pb=b'\n\x12networkstuff.proto\x12\x0cnetworkstuff\"\x1b\n\rRouterRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"S\n\x06Router\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12+\n\ninterfaces\x18\x03 \x03(\x0b\x32\x17.networkstuff.Interface\",\n\tInterface\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2O\n\rRouterService\x12>\n\tGetRouter\x12\x1b.networkstuff.RouterRequest\x1a\x14.networkstuff.RouterB!Z\x1fgithub.com/package/networkstuffb\x06proto3'
)




_ROUTERREQUEST = _descriptor.Descriptor(
  name='RouterRequest',
  full_name='networkstuff.RouterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='networkstuff.RouterRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=63,
)


_ROUTER = _descriptor.Descriptor(
  name='Router',
  full_name='networkstuff.Router',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='networkstuff.Router.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='networkstuff.Router.hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interfaces', full_name='networkstuff.Router.interfaces', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=148,
)


_INTERFACE = _descriptor.Descriptor(
  name='Interface',
  full_name='networkstuff.Interface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='networkstuff.Interface.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='networkstuff.Interface.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=194,
)

_ROUTER.fields_by_name['interfaces'].message_type = _INTERFACE
DESCRIPTOR.message_types_by_name['RouterRequest'] = _ROUTERREQUEST
DESCRIPTOR.message_types_by_name['Router'] = _ROUTER
DESCRIPTOR.message_types_by_name['Interface'] = _INTERFACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RouterRequest = _reflection.GeneratedProtocolMessageType('RouterRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTERREQUEST,
  '__module__' : 'networkstuff_pb2'
  # @@protoc_insertion_point(class_scope:networkstuff.RouterRequest)
  })
_sym_db.RegisterMessage(RouterRequest)

Router = _reflection.GeneratedProtocolMessageType('Router', (_message.Message,), {
  'DESCRIPTOR' : _ROUTER,
  '__module__' : 'networkstuff_pb2'
  # @@protoc_insertion_point(class_scope:networkstuff.Router)
  })
_sym_db.RegisterMessage(Router)

Interface = _reflection.GeneratedProtocolMessageType('Interface', (_message.Message,), {
  'DESCRIPTOR' : _INTERFACE,
  '__module__' : 'networkstuff_pb2'
  # @@protoc_insertion_point(class_scope:networkstuff.Interface)
  })
_sym_db.RegisterMessage(Interface)


DESCRIPTOR._options = None

_ROUTERSERVICE = _descriptor.ServiceDescriptor(
  name='RouterService',
  full_name='networkstuff.RouterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=196,
  serialized_end=275,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRouter',
    full_name='networkstuff.RouterService.GetRouter',
    index=0,
    containing_service=None,
    input_type=_ROUTERREQUEST,
    output_type=_ROUTER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTERSERVICE)

DESCRIPTOR.services_by_name['RouterService'] = _ROUTERSERVICE

# @@protoc_insertion_point(module_scope)
