# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networkstuff.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12networkstuff.proto\x12\x0cnetworkstuff\"\x1b\n\rRouterRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"S\n\x06Router\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12+\n\ninterfaces\x18\x03 \x03(\x0b\x32\x17.networkstuff.Interface\",\n\tInterface\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2O\n\rRouterService\x12>\n\tGetRouter\x12\x1b.networkstuff.RouterRequest\x1a\x14.networkstuff.Routerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'networkstuff_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROUTERREQUEST._serialized_start=36
  _ROUTERREQUEST._serialized_end=63
  _ROUTER._serialized_start=65
  _ROUTER._serialized_end=148
  _INTERFACE._serialized_start=150
  _INTERFACE._serialized_end=194
  _ROUTERSERVICE._serialized_start=196
  _ROUTERSERVICE._serialized_end=275
# @@protoc_insertion_point(module_scope)
