# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import networkstuff_pb2 as networkstuff__pb2


class RouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRouter = channel.unary_unary(
                '/networkstuff.RouterService/GetRouter',
                request_serializer=networkstuff__pb2.RouterRequest.SerializeToString,
                response_deserializer=networkstuff__pb2.Router.FromString,
                )


class RouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRouter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRouter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRouter,
                    request_deserializer=networkstuff__pb2.RouterRequest.FromString,
                    response_serializer=networkstuff__pb2.Router.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'networkstuff.RouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRouter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/networkstuff.RouterService/GetRouter',
            networkstuff__pb2.RouterRequest.SerializeToString,
            networkstuff__pb2.Router.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
