Vagrant.configure(2) do |config|
    config.vm.box = "vyos/current"
  
    config.vm.define "r1" do |r1|
        r1.vm.host_name = "r1"
        r1.vm.network "private_network",
                        ip: "192.168.12.11",
                        virtualbox__intnet: "01-to-02"
        r1.vm.network "private_network",
                        ip: "192.168.31.11",
                        virtualbox__intnet: "03-to-01"
    end
  
    config.vm.define "r2" do |r2|
        r2.vm.host_name = "r2"
        r2.vm.network "private_network",
                        ip: "192.168.23.12",
                        virtualbox__intnet: "02-to-03"
        r2.vm.network "private_network",
                        ip: "192.168.12.12",
                        virtualbox__intnet: "01-to-02"
    end
  
    config.vm.define "r3" do |r3|
        r3.vm.host_name = "r3"
        r3.vm.network "private_network",
                        ip: "192.168.31.13",
                        virtualbox__intnet: "03-to-01"
        r3.vm.network "private_network",
                        ip: "192.168.23.13",
                        virtualbox__intnet: "02-to-03"
    end
end
